#!/usr/bin/env bash
# NexaRail — product-flow governance flag helper
#
# TESTNET/DEVNET ONLY. Tokens have zero value. No mainnet exists.
#
# Toggles product-flow live/routing flags through the governance proposal
# path. Uses MsgUpdateParams for the relevant module. Always reads current
# on-chain params and preserves all fields except the target flag(s).
#
# Usage:
#   product-gov.sh enable-escrow-live [--confirm]
#   product-gov.sh disable-escrow-live [--confirm]
#   product-gov.sh enable-settlement-live [--confirm]
#   product-gov.sh disable-settlement-live [--confirm]
#   product-gov.sh enable-settlement-treasury-routing [--confirm]
#   product-gov.sh disable-settlement-treasury-routing [--confirm]
#   product-gov.sh enable-settlement-burn-routing [--confirm]
#   product-gov.sh disable-settlement-burn-routing [--confirm]
#   product-gov.sh enable-treasury-live [--confirm]
#   product-gov.sh disable-treasury-live [--confirm]
#   product-gov.sh enable-payout-live [--confirm]
#   product-gov.sh disable-payout-live [--confirm]
#   product-gov.sh show-live-flags
#
# Options:
#   --confirm         Submit the governance proposal, vote Yes, and wait for
#                     passage. Without this flag, the script runs in dry-run
#                     mode — it prints the proposal JSON and takes no action.
#   --chain           Chain ID (default: nexarail-agent-testnet-1)
#   --evidence-dir    Evidence output directory (auto-generated by default)
#
# Safety rules:
#   - burn routing  requires settlement live + treasury routing
#   - treasury routing  requires settlement live
set -Eeuo pipefail

# ---------------------------------------------------------------------------
# Paths & constants
# ---------------------------------------------------------------------------
PROJECT_DIR="$(cd "$(dirname "$0")" && cd ../.. && pwd)"
SCRIPT_DIR="$PROJECT_DIR/scripts/testnet"
BINARY="$PROJECT_DIR/build/nexaraild"
AGENT_DIR="$PROJECT_DIR/rehearsals/validator-agents"
CHAIN_ID="nexarail-agent-testnet-1"
DENOM="unxrl"
TX_FEE="10000$DENOM"

# bravo is the governance-proposal submitter (matches rehearsal pattern)
SUBMIT_AGENT="bravo"
SUBMIT_HOME="$AGENT_DIR/$SUBMIT_AGENT"
SUBMIT_KEY="${SUBMIT_AGENT}-key"

# bravo RPC & API ports (local 5-agent layout)
BRAVO_RPC="tcp://127.0.0.1:27667"
BRAVO_RPC_HTTP="http://127.0.0.1:27667"
BRAVO_API_PORT="1418"

# Governance authority from genesis — the x/gov module account address
GOV_ADDR="nxr10d07y265gmmuvt4z0w9aw880jnsr700js8jz70"

# Timeout for waiting on the governance proposal to pass
PROPOSAL_TIMEOUT_SEC=120

# Evidence
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
EVIDENCE_DIR=""
CONFIRM=0
AGENTS=(alpha bravo charlie delta echo)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
usage() {
    sed -n '2,/^$/p' "$0" | sed 's/^# //; s/^#$//' | grep -v '^$' | head -5
    grep '^#   product-gov' "$0" | sed 's/^#//'
    sed -n '/^# Options:/,/^# Safety rules:/p' "$0" | sed 's/^# //; s/^#$//'
}

die() {
    echo "[FATAL] $*" >&2
    local rerun_cmd="$0 $command${CONFIRM:+ --confirm}"
    echo "[FATAL] Evidence: ${EVIDENCE_DIR:-not set}" >&2
    echo "[FATAL] Rerun: $rerun_cmd" >&2
    echo "[FATAL] Common causes: node not running, incorrect chain or ports, binary not built," >&2
    echo "[FATAL]   governance authority mismatch, insufficient funds in submitter account." >&2
    exit 1
}

info()  { echo "  [INFO] $*"; }
ok()    { echo "  [OK]   $*"; }
warn()  { echo "  [WARN] $*"; }

# Allowlist of valid subcommands
VALID_COMMANDS=(
    enable-escrow-live disable-escrow-live
    enable-settlement-live disable-settlement-live
    enable-settlement-treasury-routing disable-settlement-treasury-routing
    enable-settlement-burn-routing disable-settlement-burn-routing
    enable-treasury-live disable-treasury-live
    enable-payout-live disable-payout-live
    show-live-flags
)

in_allowlist() {
    local cmd="$1"
    for v in "${VALID_COMMANDS[@]}"; do [ "$v" = "$cmd" ] && return 0; done
    return 1
}

is_true() { [ "${1:-false}" = "true" ] || [ "${1:-false}" = "True" ]; }

# ---------------------------------------------------------------------------
# REST queries
# ---------------------------------------------------------------------------
rest_get() {
    local path="$1"
    local out="$2"
    curl -s --max-time 10 "http://127.0.0.1:$BRAVO_API_PORT$path" > "$out" 2>/dev/null || return 1
    if jq -e 'type == "object" and (has("error") | not) and ((has("code") and ((.code|tostring) != "0")) | not)' "$out" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

json_get() {
    local file="$1"
    local expr="$2"
    jq -r "$expr" "$file" 2>/dev/null || echo ""
}

agent_home() { printf '%s/%s' "$AGENT_DIR" "$1"; }

agent_addr() {
    local agent="$1"
    "$BINARY" keys show "${agent}-key" -a --keyring-backend test \
        --home "$(agent_home "$agent")" 2>/dev/null || die "cannot resolve $agent address"
}

account_numbers() {
    local addr="$1"
    local outfile="$2"
    "$BINARY" query auth account "$addr" --node "$BRAVO_RPC" --output json > "$outfile" 2>/dev/null || return 1
    python3 - "$outfile" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
a = d.get("account", d)
if isinstance(a, dict) and "base_account" in a:
    a = a["base_account"]
print(a.get("account_number", "0"), a.get("sequence", "0"))
PY
}

latest_proposal_id() {
    local outfile="$1"
    "$BINARY" query gov proposals --node "$BRAVO_RPC" --output json > "$outfile" 2>/dev/null || return 1
    python3 - "$outfile" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
props = d.get("proposals", [])
if not props:
    print("")
    raise SystemExit(1)
p = props[-1]
print(p.get("id") or p.get("proposal_id") or "")
PY
}

proposal_status() {
    local proposal_id="$1"
    local outfile="$2"
    "$BINARY" query gov proposal "$proposal_id" --node "$BRAVO_RPC" --output json > "$outfile" 2>/dev/null || return 1
    python3 - "$outfile" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
p = d.get("proposal", d)
print(p.get("status", "UNKNOWN"))
PY
}

# ---------------------------------------------------------------------------
# Param loaders — read current on-chain params to preserve all but target flag
# ---------------------------------------------------------------------------
load_settlement_params() {
    local dir="$1"
    mkdir -p "$dir"
    rest_get "/nexarail/settlement/v1/params" "$dir/current-settlement-params.json" \
        || die "cannot query settlement params. Is the node running? Check BRAVO_API_PORT=$BRAVO_API_PORT and that the node REST API is enabled in app.toml."
    jq '.params' "$dir/current-settlement-params.json" > "$dir/current-settlement-params.json.tmp" && \
        mv "$dir/current-settlement-params.json.tmp" "$dir/current-settlement-params.json"
}

load_escrow_params() {
    local dir="$1"
    mkdir -p "$dir"
    rest_get "/nexarail/escrow/v1/params" "$dir/current-escrow-params.json" \
        || die "cannot query escrow params. Is the node running? Check BRAVO_API_PORT=$BRAVO_API_PORT."
    jq '.params' "$dir/current-escrow-params.json" > "$dir/current-escrow-params.json.tmp" && \
        mv "$dir/current-escrow-params.json.tmp" "$dir/current-escrow-params.json"
}

load_treasury_params() {
    local dir="$1"
    mkdir -p "$dir"
    rest_get "/nexarail/treasury/v1/params" "$dir/current-treasury-params.json" \
        || die "cannot query treasury params. Is the node running? Check BRAVO_API_PORT=$BRAVO_API_PORT."
    jq '.params' "$dir/current-treasury-params.json" > "$dir/current-treasury-params.json.tmp" && \
        mv "$dir/current-treasury-params.json.tmp" "$dir/current-treasury-params.json"
}

load_payout_params() {
    local dir="$1"
    mkdir -p "$dir"
    rest_get "/nexarail/payout/v1/params" "$dir/current-payout-params.json" \
        || die "cannot query payout params. Is the node running? Check BRAVO_API_PORT=$BRAVO_API_PORT."
    jq '.params' "$dir/current-payout-params.json" > "$dir/current-payout-params.json.tmp" && \
        mv "$dir/current-payout-params.json.tmp" "$dir/current-payout-params.json"
}

# ---------------------------------------------------------------------------
# Safety validators
# ---------------------------------------------------------------------------
check_safety() {
    local command="$1"
    local dir="$2"

    # burn routing
    if [[ "$command" == *burn-routing* ]] && [[ "$command" == enable-* ]]; then
        load_settlement_params "$dir/safety-check"
        local live treasury
        live="$(json_get "$dir/safety-check/current-settlement-params.json" '.live_enabled // "false"')"
        treasury="$(json_get "$dir/safety-check/current-settlement-params.json" '.treasury_routing_enabled // "false"')"
        if ! is_true "$live"; then
            die "SAFETY: burn routing requires settlement live_enabled=true (currently $live). Enable settlement live first."
        fi
        if ! is_true "$treasury"; then
            die "SAFETY: burn routing requires treasury_routing_enabled=true (currently $treasury). Enable treasury routing first."
        fi
        ok "safety check passed: settlement live=$live treasury_routing=$treasury"
    fi

    # treasury routing
    if [[ "$command" == *treasury-routing* ]] && [[ "$command" == enable-* ]]; then
        load_settlement_params "$dir/safety-check"
        local live
        live="$(json_get "$dir/safety-check/current-settlement-params.json" '.live_enabled // "false"')"
        if ! is_true "$live"; then
            die "SAFETY: treasury routing requires settlement live_enabled=true (currently $live). Enable settlement live first."
        fi
        ok "safety check passed: settlement live=$live"
    fi

    rm -rf "$dir/safety-check" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Proposal builders — produce the full MsgUpdateParams JSON
# ---------------------------------------------------------------------------
build_settlement_proposal_msg() {
    local dir="$1"
    local live="$2"
    local treasury="$3"
    local burn="$4"
    load_settlement_params "$dir"
    local params_json
    params_json="$(cat "$dir/current-settlement-params.json")"

    # Override the target flags
    params_json="$(echo "$params_json" | jq \
        --argjson live "$live" \
        --argjson treasury "$treasury" \
        --argjson burn "$burn" \
        '.live_enabled = $live | .treasury_routing_enabled = $treasury | .burn_routing_enabled = $burn')"

    cat <<EOF
    {
      "@type": "/nexarail.settlement.v1.MsgUpdateParams",
      "authority": "$GOV_ADDR",
      "params": $params_json
    }
EOF
}

build_escrow_proposal_msg() {
    local dir="$1"
    local live="$2"
    load_escrow_params "$dir"
    local params_json
    params_json="$(cat "$dir/current-escrow-params.json")"
    params_json="$(echo "$params_json" | jq --argjson live "$live" '.live_enabled = $live')"

    cat <<EOF
    {
      "@type": "/nexarail.escrow.v1.MsgUpdateParams",
      "authority": "$GOV_ADDR",
      "params": $params_json
    }
EOF
}

build_treasury_proposal_msg() {
    local dir="$1"
    local live="$2"
    load_treasury_params "$dir"
    local params_json
    params_json="$(cat "$dir/current-treasury-params.json")"
    params_json="$(echo "$params_json" | jq --argjson live "$live" '.live_enabled = $live')"

    cat <<EOF
    {
      "@type": "/nexarail.treasury.v1.MsgUpdateParams",
      "authority": "$GOV_ADDR",
      "params": $params_json
    }
EOF
}

build_payout_proposal_msg() {
    local dir="$1"
    local live="$2"
    load_payout_params "$dir"
    local params_json
    params_json="$(cat "$dir/current-payout-params.json")"
    params_json="$(echo "$params_json" | jq --argjson live "$live" '.live_enabled = $live')"

    cat <<EOF
    {
      "@type": "/nexarail.payout.v1.MsgUpdateParams",
      "authority": "$GOV_ADDR",
      "params": $params_json
    }
EOF
}

# ---------------------------------------------------------------------------
# Proposal submission & governance lifecycle
# ---------------------------------------------------------------------------
submit_gov_proposal() {
    local label="$1"
    local dir="$2"
    local title="$3"
    local msg_json="$4"

    local bravo_addr account_number sequence proposal_id tx_hash
    mkdir -p "$dir"

    bravo_addr="$(agent_addr "$SUBMIT_AGENT")"
    read -r account_number sequence < <(account_numbers "$bravo_addr" "$dir/bravo-account.json") \
        || die "cannot read account numbers for $bravo_addr. Check that the agent key exists at $SUBMIT_HOME and the node is reachable at $BRAVO_RPC."
    echo "account_number=$account_number sequence=$sequence" > "$dir/signing-account.txt"

    # Write proposal JSON
    cat > "$dir/proposal.json" <<EOF
{
  "title": "$title",
  "summary": "Governance toggle on agent-testnet. TESTNET ONLY — tokens have zero value. No mainnet implications.",
  "messages": [
$msg_json
  ],
  "metadata": "",
  "deposit": "1000000$DENOM",
  "expedited": false
}
EOF

    info "generating unsigned proposal..."
    if ! "$BINARY" tx gov submit-proposal "$dir/proposal.json" \
        --from "$SUBMIT_KEY" --keyring-backend test --home "$SUBMIT_HOME" \
        --chain-id "$CHAIN_ID" --node "$BRAVO_RPC" \
        --generate-only --fees "$TX_FEE" \
        > "$dir/unsigned.json" 2> "$dir/unsigned.err"; then
        die "proposal generate-only failed. See $dir/unsigned.err for details."
    fi

    info "signing proposal..."
    if ! "$BINARY" tx sign "$dir/unsigned.json" \
        --offline --account-number "$account_number" --sequence "$sequence" \
        --from "$SUBMIT_KEY" --keyring-backend test --home "$SUBMIT_HOME" \
        --chain-id "$CHAIN_ID" \
        > "$dir/signed.json" 2> "$dir/signed.err"; then
        die "proposal signing failed. Common cause: account sequence mismatch if a prior tx was broadcast but not confirmed. See $dir/signed.err and $dir/signing-account.txt."
    fi

    # Broadcast via raw CometBFT RPC (same pattern as rehearsal)
    info "broadcasting signed proposal..."
    local encoded_b64
    encoded_b64="$("$BINARY" tx encode "$dir/signed.json" | tr -d '\n')"
    echo -n "$encoded_b64" > "$dir/signed.b64"

    curl -s --max-time 15 "$BRAVO_RPC_HTTP/" \
        -H "Content-Type: application/json" \
        -d "{\"jsonrpc\":\"2.0\",\"method\":\"broadcast_tx_sync\",\"params\":{\"tx\":\"${encoded_b64}\"},\"id\":1}" \
        > "$dir/broadcast-cometbft.json"

    tx_hash="$(json_get "$dir/broadcast-cometbft.json" '.result.hash // ""')"
    local code check_tx_code
    code="$(json_get "$dir/broadcast-cometbft.json" '.result.code // 1')"
    check_tx_code="$(json_get "$dir/broadcast-cometbft.json" '.result.code // 1')"
    echo "$tx_hash" > "$dir/txhash.txt"
    echo "$code" > "$dir/checktx-code.txt"

    if [ -z "$tx_hash" ] || [ "$code" != "0" ]; then
        die "broadcast failed tx_hash=${tx_hash:-missing} code=${code:-missing}. Check $dir/broadcast-cometbft.json for full response."
    fi
    ok "proposal broadcast tx_hash=$tx_hash"

    # Wait for inclusion
    if ! wait_for_tx "$tx_hash" "$dir/submit-tx.json" "$label"; then
        die "proposal tx $tx_hash not included before timeout"
    fi

    proposal_id="$(latest_proposal_id "$dir/proposals-after-submit.json")" \
        || die "cannot read back proposal ID after submission"
    echo "$proposal_id" > "$dir/proposal-id.txt"
    ok "proposal ID=$proposal_id"

    # Vote all agents Yes
    vote_all_yes "$proposal_id" "$dir" "$label"

    # Wait for passage
    wait_for_proposal_passed "$proposal_id" "$dir" "$label" || {
        local final_status
        final_status="$(cat "$dir/proposal-status-latest.txt" 2>/dev/null || echo "unknown")"
        warn "proposal $proposal_id did not pass; final status=$final_status"
        echo "$final_status" > "$dir/final-status.txt"
        return 1
    }
}

# ---------------------------------------------------------------------------
# Governance lifecycle primitives (from rehearsal patterns)
# ---------------------------------------------------------------------------
wait_for_tx() {
    local tx_hash="$1"
    local outfile="$2"
    local label="$3"
    local rpc_hash

    rpc_hash="$tx_hash"
    case "$rpc_hash" in 0x*|0X*) ;; *) rpc_hash="0x$rpc_hash" ;; esac

    for _ in $(seq 1 30); do
        curl -s --max-time 10 "$BRAVO_RPC_HTTP/tx?hash=$rpc_hash" > "$outfile" 2>/dev/null || true
        if jq -e '.result.hash' "$outfile" >/dev/null 2>&1; then
            local code
            code="$(json_get "$outfile" '.result.tx_result.code // 0')"
            if [ "$code" = "0" ]; then
                ok "$label included code=0"
                return 0
            fi
            die "$label included code=$code"
        fi
        sleep 2
    done
    die "$label not found by CometBFT tx query"
}

wait_for_proposal_passed() {
    local proposal_id="$1"
    local dir="$2"
    local label="$3"
    local status
    local waited=0

    while [ "$waited" -lt "$PROPOSAL_TIMEOUT_SEC" ]; do
        status="$(proposal_status "$proposal_id" "$dir/proposal-status-${waited}.json" 2>/dev/null || echo "UNKNOWN")"
        echo "$status" > "$dir/proposal-status-latest.txt"
        if [ "$status" = "PROPOSAL_STATUS_PASSED" ]; then
            cp "$dir/proposal-status-${waited}.json" "$dir/proposal-final-status.json"
            ok "$label proposal $proposal_id passed"
            return 0
        fi
        if [ "$status" = "PROPOSAL_STATUS_FAILED" ] || [ "$status" = "PROPOSAL_STATUS_REJECTED" ]; then
            cp "$dir/proposal-status-${waited}.json" "$dir/proposal-final-status.json"
            warn "$label proposal $proposal_id final status=$status. Check $dir/proposal-status-*.json for the full proposal status record."
            return 1
        fi
        sleep 5
        waited=$((waited + 5))
    done

    warn "$label proposal $proposal_id did not pass before ${PROPOSAL_TIMEOUT_SEC}s timeout; latest=$status. Common causes: insufficient deposit, voting power not reached, or node not progressing."
    echo "  [WARN] Check $dir/proposal-status-*.json for status history." >&2
    return 1
}

vote_all_yes() {
    local proposal_id="$1"
    local dir="$2"
    local label="$3"
    mkdir -p "$dir/votes"
    : > "$dir/vote-tx-hashes.txt"

    for agent in "${AGENTS[@]}"; do
        local outfile="$dir/votes/${agent}-vote.json"
        if ! "$BINARY" tx gov vote "$proposal_id" yes \
            --from "${agent}-key" --keyring-backend test \
            --home "$(agent_home "$agent")" \
            --chain-id "$CHAIN_ID" \
            --node "$BRAVO_RPC" \
            --fees "2000$DENOM" \
            --broadcast-mode sync \
            --output json \
            -y > "$outfile" 2>/dev/null; then
            warn "$label $agent vote command failed. Check that agent '$agent' key exists at $(agent_home "$agent")."
            continue
        fi
        local tx_hash code
        tx_hash="$(json_get "$outfile" '.txhash // ""')"
        code="$(json_get "$outfile" '.code // 0')"
        if [ -n "$tx_hash" ] && [ "$code" = "0" ]; then
            echo "$agent $tx_hash" >> "$dir/vote-tx-hashes.txt"
            ok "$label $agent vote submitted tx_hash=$tx_hash"
        else
            warn "$label $agent vote tx_hash=${tx_hash:-missing} code=${code:-missing}. Check $outfile for broadcast response."
        fi
        sleep 1
    done
}

# ---------------------------------------------------------------------------
# Live flag display
# ---------------------------------------------------------------------------
show_live_flags() {
    local dir="$1"
    mkdir -p "$dir"
    echo ""
    echo "╔═══════════════════════════════════════════════════╗"
    echo "║  NexaRail Product Live Flags                     ║"
    echo "║  $(date -u +%Y-%m-%dT%H:%M:%SZ) UTC             ║"
    echo "╚═══════════════════════════════════════════════════╝"

    if rest_get "/nexarail/settlement/v1/params" "$dir/settlement-params.json"; then
        echo ""
        echo "settlement:"
        echo "  live_enabled=$(json_get "$dir/settlement-params.json" '.params.live_enabled // "query_failed"')"
        echo "  treasury_routing_enabled=$(json_get "$dir/settlement-params.json" '.params.treasury_routing_enabled // "query_failed"')"
        echo "  burn_routing_enabled=$(json_get "$dir/settlement-params.json" '.params.burn_routing_enabled // "query_failed"')"
    else
        warn "settlement params query failed — REST endpoint $BRAVO_API_PORT/nexarail/settlement/v1/params unreachable."
    fi

    if rest_get "/nexarail/escrow/v1/params" "$dir/escrow-params.json"; then
        echo ""
        echo "escrow:"
        echo "  live_enabled=$(json_get "$dir/escrow-params.json" '.params.live_enabled // "query_failed"')"
    else
        warn "escrow params query failed — REST endpoint $BRAVO_API_PORT/nexarail/escrow/v1/params unreachable."
    fi

    if rest_get "/nexarail/treasury/v1/params" "$dir/treasury-params.json"; then
        echo ""
        echo "treasury:"
        echo "  live_enabled=$(json_get "$dir/treasury-params.json" '.params.live_enabled // "query_failed"')"
    else
        warn "treasury params query failed — REST endpoint $BRAVO_API_PORT/nexarail/treasury/v1/params unreachable."
    fi

    if rest_get "/nexarail/payout/v1/params" "$dir/payout-params.json"; then
        echo ""
        echo "payout:"
        echo "  live_enabled=$(json_get "$dir/payout-params.json" '.params.live_enabled // "query_failed"')"
    else
        warn "payout params query failed — REST endpoint $BRAVO_API_PORT/nexarail/payout/v1/params unreachable."
    fi
    echo ""
}

# ---------------------------------------------------------------------------
# Evidence writing
# ---------------------------------------------------------------------------
write_evidence() {
    local command="$1"
    local label="$2"
    local proposal_id="${3:-}"
    local tx_hash="${4:-}"
    local dir="$EVIDENCE_DIR"
    local evidence_file="$dir/result.json"

    cat > "$evidence_file" <<EOF
{
  "command": "$command",
  "label": "$label",
  "proposal_id": $(if [ -n "$proposal_id" ]; then echo "\"$proposal_id\""; else echo "null"; fi),
  "tx_hash": $(if [ -n "$tx_hash" ]; then echo "\"$tx_hash\""; else echo "null"; fi),
  "chain_id": "$CHAIN_ID",
  "confirm": $CONFIRM,
  "timestamp_utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "evidence_dir": "$dir",
  "network": "agent-testnet"
}
EOF

    # Also dump current flags for context
    show_live_flags "$dir/after-flags" > "$dir/after-flags-output.txt" 2>&1 || true

    ok "evidence written: $evidence_file"
}

# ---------------------------------------------------------------------------
# Main dispatcher
# ---------------------------------------------------------------------------
main() {
    local command=""
    local custom_chain=""

    # Parse arguments (positional: command first)
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --confirm) CONFIRM=1; shift ;;
            --chain) custom_chain="${2:-}"; shift 2 ;;
            --evidence-dir) EVIDENCE_DIR="${2:-}"; shift 2 ;;
            -h|--help) usage; exit 0 ;;
            -*)
                if in_allowlist "$1"; then
                    command="$1"; shift
                else
                    die "unknown option: $1. Try -h for help."
                fi
                ;;
            *)
                if [ -z "$command" ] && in_allowlist "$1"; then
                    command="$1"; shift
                else
                    die "unknown argument: $1"
                fi
                ;;
        esac
    done

    [ -z "$command" ] && { usage; exit 2; }

    # Override chain if provided
    [ -n "$custom_chain" ] && CHAIN_ID="$custom_chain"

    # Set up evidence directory
    if [ -z "$EVIDENCE_DIR" ]; then
        EVIDENCE_DIR="$AGENT_DIR/product-flows/gov-toggles/$TIMESTAMP"
    fi
    mkdir -p "$EVIDENCE_DIR"

    echo "╔══════════════════════════════════════════════════════╗"
    echo "║  NexaRail Product-Flow Governance Toggle            ║"
    echo "║  TESTNET/DEVNET ONLY                                ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo "command:   $command"
    echo "chain:     $CHAIN_ID"
    echo "evidence:  $EVIDENCE_DIR"
    echo "confirm:   $([[ $CONFIRM -eq 1 ]] && echo yes || echo no dry-run)"
    echo ""

    # Validate binary
    if [ ! -x "$BINARY" ]; then
        die "binary not found at $BINARY. Run 'make build' first."
    fi

    # -----------------------------------------------------------------------
    # show-live-flags — just query and exit
    # -----------------------------------------------------------------------
    if [ "$command" = "show-live-flags" ]; then
        show_live_flags "$EVIDENCE_DIR"
        write_evidence "$command" "show-live-flags"
        exit 0
    fi

    # -----------------------------------------------------------------------
    # Safety checks before any enable that has dependency constraints
    # -----------------------------------------------------------------------
    check_safety "$command" "$EVIDENCE_DIR"

    # -----------------------------------------------------------------------
    # Determine target flag changes and build the proposal message
    # -----------------------------------------------------------------------
    local msg_json=""
    local label=""
    local target_value

    case "$command" in
        enable-escrow-live)
            target_value="true"; label="gov-enable-escrow-live"
            msg_json="$(build_escrow_proposal_msg "$EVIDENCE_DIR" true)"
            ;;
        disable-escrow-live)
            target_value="false"; label="gov-disable-escrow-live"
            msg_json="$(build_escrow_proposal_msg "$EVIDENCE_DIR" false)"
            ;;
        enable-settlement-live)
            target_value="true"; label="gov-enable-settlement-live"
            # preserve current treasury/burn routing from on-chain params
            load_settlement_params "$EVIDENCE_DIR"
            local cur_treasury cur_burn
            cur_treasury="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.treasury_routing_enabled // "false"')"
            cur_burn="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.burn_routing_enabled // "false"')"
            msg_json="$(build_settlement_proposal_msg "$EVIDENCE_DIR" true "$cur_treasury" "$cur_burn")"
            ;;
        disable-settlement-live)
            target_value="false"; label="gov-disable-settlement-live"
            load_settlement_params "$EVIDENCE_DIR"
            local cur_treasury cur_burn
            cur_treasury="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.treasury_routing_enabled // "false"')"
            cur_burn="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.burn_routing_enabled // "false"')"
            msg_json="$(build_settlement_proposal_msg "$EVIDENCE_DIR" false "$cur_treasury" "$cur_burn")"
            ;;
        enable-settlement-treasury-routing)
            target_value="true"; label="gov-enable-settlement-treasury-routing"
            load_settlement_params "$EVIDENCE_DIR"
            local cur_live cur_burn
            cur_live="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.live_enabled // "false"')"
            cur_burn="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.burn_routing_enabled // "false"')"
            msg_json="$(build_settlement_proposal_msg "$EVIDENCE_DIR" "$cur_live" true "$cur_burn")"
            ;;
        disable-settlement-treasury-routing)
            target_value="false"; label="gov-disable-settlement-treasury-routing"
            load_settlement_params "$EVIDENCE_DIR"
            local cur_live cur_burn
            cur_live="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.live_enabled // "false"')"
            cur_burn="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.burn_routing_enabled // "false"')"
            msg_json="$(build_settlement_proposal_msg "$EVIDENCE_DIR" "$cur_live" false "$cur_burn")"
            ;;
        enable-settlement-burn-routing)
            target_value="true"; label="gov-enable-settlement-burn-routing"
            load_settlement_params "$EVIDENCE_DIR"
            local cur_live cur_treasury
            cur_live="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.live_enabled // "false"')"
            cur_treasury="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.treasury_routing_enabled // "false"')"
            msg_json="$(build_settlement_proposal_msg "$EVIDENCE_DIR" "$cur_live" "$cur_treasury" true)"
            ;;
        disable-settlement-burn-routing)
            target_value="false"; label="gov-disable-settlement-burn-routing"
            load_settlement_params "$EVIDENCE_DIR"
            local cur_live cur_treasury
            cur_live="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.live_enabled // "false"')"
            cur_treasury="$(json_get "$EVIDENCE_DIR/current-settlement-params.json" '.treasury_routing_enabled // "false"')"
            msg_json="$(build_settlement_proposal_msg "$EVIDENCE_DIR" "$cur_live" "$cur_treasury" false)"
            ;;
        enable-treasury-live)
            target_value="true"; label="gov-enable-treasury-live"
            msg_json="$(build_treasury_proposal_msg "$EVIDENCE_DIR" true)"
            ;;
        disable-treasury-live)
            target_value="false"; label="gov-disable-treasury-live"
            msg_json="$(build_treasury_proposal_msg "$EVIDENCE_DIR" false)"
            ;;
        enable-payout-live)
            target_value="true"; label="gov-enable-payout-live"
            msg_json="$(build_payout_proposal_msg "$EVIDENCE_DIR" true)"
            ;;
        disable-payout-live)
            target_value="false"; label="gov-disable-payout-live"
            msg_json="$(build_payout_proposal_msg "$EVIDENCE_DIR" false)"
            ;;
    esac

    if [ -z "$label" ] || [ -z "$msg_json" ]; then
        die "internal error: could not build proposal for command=$command"
    fi

    # Print the proposal JSON
    local title
    title="TESTNET: ${command} -- ${label}"
    cat > "$EVIDENCE_DIR/proposal-print.json" <<EOF
{
  "title": "$title",
  "summary": "Governance toggle on agent-testnet. TESTNET ONLY — tokens have zero value. No mainnet implications.",
  "messages": [
$msg_json
  ],
  "metadata": "",
  "deposit": "1000000$DENOM",
  "expedited": false
}
EOF

    echo ""
    echo "--- Proposal summary ---"
    echo "Module: $(echo "$label" | sed 's/^gov-//; s/-enable-.*//; s/-disable-.*//')"
    echo "Target: $command"
    echo "Proposal JSON written: $EVIDENCE_DIR/proposal-print.json"
    echo ""
    echo "Proposal messages:"
    echo "$msg_json" | jq '.' 2>/dev/null || echo "$msg_json"

    # -----------------------------------------------------------------------
    # Dry-run mode — just print and exit
    # -----------------------------------------------------------------------
    if [ "$CONFIRM" -eq 0 ]; then
        echo ""
        warn "DRY-RUN — no action taken. Re-run with --confirm to submit."
        echo ""
        info "To submit this proposal:"
        echo "  $0 $command --confirm"
        info "To re-run in dry-run mode:"
        echo "  $0 $command"
        info "Evidence from this dry run: $EVIDENCE_DIR"
        echo ""

        write_evidence "$command" "$label"
        exit 0
    fi

    # -----------------------------------------------------------------------
    # Confirm mode — submit governance proposal
    # -----------------------------------------------------------------------
    echo ""
    info "CONFIRMED — submitting governance proposal: $command"
    info "Evidence: $EVIDENCE_DIR"
    echo ""

    submit_gov_proposal "$label" "$EVIDENCE_DIR/gov" "$title" "$msg_json"

    local proposal_id tx_hash
    proposal_id="$(cat "$EVIDENCE_DIR/gov/proposal-id.txt" 2>/dev/null || echo "")"
    tx_hash="$(cat "$EVIDENCE_DIR/gov/txhash.txt" 2>/dev/null || echo "")"

    echo ""
    echo "╔══════════════════════════════════════════════════════╗"
    echo "║  Governance toggle complete                          ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo "Command:      $command"
    echo "Proposal ID:  $proposal_id"
    echo "Tx hash:      $tx_hash"
    echo "Evidence:     $EVIDENCE_DIR"
    echo "Rerun:        $0 $command --confirm --chain $CHAIN_ID"
    echo ""
    info "If the flag is still not correct, check evidence and re-run the toggle."

    write_evidence "$command" "$label" "$proposal_id" "$tx_hash"

    # Verify the flag changed
    echo ""
    echo "--- Post-toggle flag verification ---"
    show_live_flags "$EVIDENCE_DIR/post-verify"
}

main "$@"
